apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  mongodb-uri: "mongodb://mongo_admin:mongo_admin_password@mongodb-service:27017/digital_classroom?authSource=admin&replicaSet=rs0"
  postgres-uri: "postgresql://postgres:postgres_password@postgres-service:5432/digital_classroom"
  redis-password: "redis_password"
  jwt-secret: "change_me_to_a_secure_random_string_in_production"
  qr-secret: "change_me_to_a_secure_random_string_too"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
stringData:
  postgres-user: "postgres"
  postgres-password: "postgres_password"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
type: Opaque
stringData:
  mongo-root-username: "mongo_admin"
  mongo-root-password: "mongo_admin_password"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
type: Opaque
stringData:
  redis-password: "redis_password"
